program: MTL Segformer Diceloss.py
project: Delete_Later
method: grid
name: MTL_Segformer_Diceloss
metric:
  name: test_mean_iou
  goal: maximize
parameters:
  epochs:
    value: 200
  backbone:
    values: ["nvidia/segformer-b0-finetuned-ade-512-512", "nvidia/segformer-b1-finetuned-ade-512-512", "nvidia/segformer-b2-finetuned-ade-512-512", "nvidia/segformer-b3-finetuned-ade-512-512", "nvidia/segformer-b4-finetuned-ade-512-512"]
  weights:
    value: None